### ISSUE TITLE
to use the latest version of jinja 2 ?

### ISSUE THREAD

**Issue by anukaal** [pyvideo/pyvideo#288]
can we use the latest version of `Jinja2==3.0.2`

**Comment by logston** [comment]
Sure!

**Comment by asweigart** [comment]
Currently, upgrading Jinja2 to 3.0.0+ also updates markupsafe from 1.1.1 to 3.0.2, which Pelican 3.6.3 isn't compatible with:

```
Traceback (most recent call last):
  File "/Users/al/github/pyvideo/.venv/bin/pelican", line 4, in <module>
    from pelican import main
  File "/Users/al/github/pyvideo/.venv/lib/python3.9/site-packages/pelican/__init__.py", line 20, in <module>
    from pelican.generators import (ArticlesGenerator, PagesGenerator,
  File "/Users/al/github/pyvideo/.venv/lib/python3.9/site-packages/pelican/generators.py", line 20, in <module>
    from pelican.cache import FileStampDataCacher
  File "/Users/al/github/pyvideo/.venv/lib/python3.9/site-packages/pelican/cache.py", line 11, in <module>
    from pelican.utils import mkdir_p
  File "/Users/al/github/pyvideo/.venv/lib/python3.9/site-packages/pelican/utils.py", line 24, in <module>
    from jinja2 import Markup
ImportError: cannot import name 'Markup' from 'jinja2' (/Users/al/github/pyvideo/.venv/lib/python3.9/site-packages/jinja2/__init__.py)
```

So until we update Pelican, we can't update Jinja2.
